services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"
    networks:
      - event-app-network
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: event-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: event_app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - event-app-network

  node:
    image: node:20-alpine
    container_name: event-app-node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - event-app-network
    depends_on:
      - app

networks:
  event-app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local

